import type { Metadata } from "next";
import "./globals.css";
import { headers } from "next/headers";

import { cookieToInitialState } from "wagmi";

import { config } from "./config/walletConnectConfig";
import Web3ModalProvider from "./context/walletContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body>
        <Web3ModalProvider initialState={initialState}>
          
          {children}
        </Web3ModalProvider>
      </body>
    </html>
  );
}
